version: "3.8"
services:
  mongo:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_USERNAME=doadmin
      - MONGO_PASSWORD=DL87gV3945rOK10k
      - MONGO_HOSTNAME=mongodb+srv://db-mongodb-sfo3-78703-0be25791.mongo.ondigitalocean.com
      - MONGO_PORT=27017
      - MONGO_DB=admin
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3001:3001
    environment:
      - DB_HOST=mongodb
      - DB_NAME=admin
      - DB_PORT=27017
      - DB_HOSTNAME=localhostdoc
    stdin_open: true
    tty: true
volumes:
  db: