version: "3.8"
services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_LOCAL_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_DOCKER_PORT
  app:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$MONGO_HOSTNAME
      - DB_NAME=$MONGO_DB
      - DB_PORT=$MONGO_LOCAL_PORT
      - DB_HOSTNAME=$MONGO_HOSTNAME
    stdin_open: true
    tty: true